name: snap_scribe
description: "Snap it, Send it, Read it. Turn photos and audio into words with a snap of your finger!"

publish_to: 'none'

flutter:
  uses-material-design: true

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1   # to ask for permission for camera and microphone
  image_picker: ^1.1.2          # for picking images from camera
  path_provider: ^2.0.11        # to find local storage directories
  crypto: ^3.0.1                # for generating hashes (sha256)
  intl: ^0.19.0                 # for date formatting
  record: ^5.0.5                # to record audio
  just_audio: ^0.9.38           # to play audio
  http: ^1.2.2                  # to handle HTTP requests (API calls)
